<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Add Project Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'blee01@college.harvard.edu',
		'to' => 'blee01@college.harvard.edu'
	),
	'fields' => array(
		'custom_U797' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Title of Intervention',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Title of Intervention\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'What was the intervention?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'What was the intervention?\' is required.',
				'format' => 'Field \'What was the intervention?\' has an invalid email.'
			)
		),
		'custom_U793' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'What resources were used?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'What resources were used?\' is required.'
			)
		),
		'custom_U789' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Who participated in implementing the intervention, and in what way?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Who participated in implementing the intervention, and in what way?\' is required.'
			)
		),
		'custom_U772' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'What was the budget? (Choose one)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'What was the budget? (Choose one)\' is required.'
			)
		),
		'custom_U781' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'How long did it take to implement (in months)?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'How long did it take to implement (in months)?\' is required.'
			)
		),
		'custom_U777' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'What are the results so far?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'What are the results so far?\' is required.'
			)
		),
		'custom_U897' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Custom:',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Custom:\' is required.'
			)
		)
	)
);

process_form($form);
?>
